// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class SortField {
    "Name": string;
    "Order": string;

    /** Creates a new SortField instance. */
    constructor($$source: Partial<SortField> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Order" in $$source)) {
            this["Order"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SortField instance from a string or object.
     */
    static createFrom($$source: any = {}): SortField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SortField($$parsedSource as Partial<SortField>);
    }
}
