// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class WoodSpecType {
    "Id": number;
    "Name": string;

    /** Creates a new WoodSpecType instance. */
    constructor($$source: Partial<WoodSpecType> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WoodSpecType instance from a string or object.
     */
    static createFrom($$source: any = {}): WoodSpecType {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WoodSpecType($$parsedSource as Partial<WoodSpecType>);
    }
}
