// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function ExportAllEntities(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(561908307) as any;
    return $resultPromise;
}

export function ImportAllEntities(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1390426902) as any;
    return $resultPromise;
}
