// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ExcelModule from "./excelmodule.js";
import * as WoodSpecTypeService from "./woodspectypeservice.js";
export {
    ExcelModule,
    WoodSpecTypeService
};

export * from "./models.js";
